spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/associationDB
    username: postgres
    password: 1593
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect